---
- name: backup database
  hosts: all
  vars:
      name: lisa
  tasks:
    - name: create backup script
      template:
        src: backup.j2
        dest: /tmp/backup.sh
        owner: ansible
        mode: u=rwx
    - name: execute script
      shell: "/tmp/backup.sh"
    - name: remove file
      file: 
        path: /tmp/backup.sh
        state: absent