# this is an example for using encrypted variables
- name: hosts group variables example
  hosts: ubuntu
  vars_files:
    - secret.yml
  tasks:
    - name: testing secret variables 1
      debug:
        msg: "user is {{ user }}"
    - name: testing secret variables 1
      debug:
        msg: "Password is {{ pass }}"